#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026 Free Mobile -- Vincent Jardin
#
# events2seq.py -- convert a lan80xx-spid event log (-L) into a
# lan80xx_bringup sequence file.
#
#   lan80xx-spid -d /dev/spidevX.Y -L /tmp/spid.events ... (record a
#   known-good MEPA bring-up through the proxy)
#   events2seq.py --client mesa-demo < spid.events > bringup.seq
#
# Keeps the WRITE ops of the chosen client (reads have no state effect
# on replay), and inserts P pauses where the original stream had gaps
# > 50 ms (clamped to 20..500 ms) so settle/poll windows are honored.
# Append V verify lines by hand for the final link checks.

import argparse
import re
import sys

# DTS cell encoding (--format dts), consumed by U-Boot
# board/nxp/lx2160a/nbxv3/lan80xx_seq.c:
#   cell0 bits 27:24 = opcode (1=W 2=R 3=P 4=V),
#         bits 22:0  = slice<<21 | mmd<<16 | reg (the SPI wire address)
#   W: cell1 = value     R: cell1 = 0     P: cell1 = ms
#   V: cell1 = mask, cell2 = expect
OP_W, OP_R, OP_P, OP_V = 1, 2, 3, 4

OP = re.compile(
    r"^(\d+) C\d+\(([^)]*)\) seq=\d+ OP W s(\d) ([0-9a-f]{2}) ([0-9a-f]{4})"
    r" = ([0-9a-f]{8})(?: (.*))?")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--client", default="mesa-demo",
                    help="process name whose writes to keep")
    ap.add_argument("--gap-ms", type=int, default=50,
                    help="insert a pause when the gap exceeds this")
    ap.add_argument("--format", choices=["seq", "dts"], default="seq",
                    help="text sequence (default) or a dtsi property "
                         "fragment for the U-Boot lan80xx_seq replayer")
    args = ap.parse_args()

    if args.format == "dts":
        cells = []
        notes = []
        last_ts = None
        n = 0
        for line in sys.stdin:
            m = OP.match(line)
            if not m or m.group(2) != args.client:
                continue
            ts = int(m.group(1))
            if last_ts is not None:
                gap_ms = (ts - last_ts) // 1000
                if gap_ms > args.gap_ms:
                    cells += [OP_P << 24, max(20, min(gap_ms, 500))]
            last_ts = ts
            addr = (int(m.group(3)) << 21 | int(m.group(4), 16) << 16 |
                    int(m.group(5), 16))
            cells += [(OP_W << 24) | addr, int(m.group(6), 16)]
            n += 1
        print("/* generated by events2seq.py --format dts -- DO NOT EDIT.")
        print(" * %d writes captured from a known-good MEPA bring-up via" % n)
        print(" * the lan80xx-spid -L event log; replayed by U-Boot's")
        print(" * lan80xx_seq command. Cell format documented in")
        print(" * lan80xx-tools/scripts/events2seq.py. */")
        print("microchip,bringup-seq = <")
        for i in range(0, len(cells), 8):
            print("\t" + " ".join("0x%08x" % c for c in cells[i:i + 8]))
        print(">;")
        print("# %d writes -> %d cells" % (n, len(cells)), file=sys.stderr)
        return

    last_ts = None
    last_slice = None
    n = 0
    print("# generated by events2seq.py -- lan80xx_bringup sequence")
    print("# source client: %s" % args.client)
    print("# columns: W <slice> <mmd> <reg> <value>  # <symbolic name from")
    print("# the lan80xx-spid event log: GLOBAL = MMD 0x1e (id/fuses/straps/")
    print("# MCU), {HOST,LINE}_PMA8_CMU_xx/LANE_xx = the paged 8-bit SerDes")
    print("# space (CMU_FF = page select), MB_* = MCU mailbox>")
    for line in sys.stdin:
        m = OP.match(line)
        if not m or m.group(2) != args.client:
            continue
        ts = int(m.group(1))
        if last_ts is not None:
            gap_ms = (ts - last_ts) // 1000
            if gap_ms > args.gap_ms:
                print("# -- %d ms gap in the original stream (settle/poll"
                      " window)" % gap_ms)
                print("P %d" % max(20, min(gap_ms, 500)))
        last_ts = ts
        if m.group(3) != last_slice:
            print("# ---- slice %s (s1 = first active port, s0 = second;"
                  " EDSx-reversed map) ----" % m.group(3))
            last_slice = m.group(3)
        name = (m.group(7) or "").strip()
        print("W %s %s %s %s%s" % (m.group(3), m.group(4), m.group(5),
                                   m.group(6),
                                   ("  # " + name) if name else ""))
        n += 1
    print("# %d writes" % n, file=sys.stderr)

if __name__ == "__main__":
    main()
